---
# tasks file for nginx_custom
- name: Меняем имя машины
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when: "inventory_hostname != ansible_hostname"

- name: установка nginx
  apt:
    name: "nginx"
    state: present

- name: Настройка прокси
  ansible.builtin.template:
    src: proxy_conf.j2
    dest: /etc/nginx/sites-available/default
  when: "'balance-server' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_1
  notify: "Nginx Reloader"
