---
# handlers file for zabbix
#- name: Reload firewalld
#  service:
#    name: ufw
#    state: reloaded
#  listen: "FW Reloader"
  
- name: zabbix-server Reloader
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: yes
  listen: "zabbix" 
  
- name: zabbix-agent Reloader
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  listen: "zabbix" 
  
- name: nginx Reloader
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
  listen: "zabbix" 
  
- name: php8.1-fpm Reloader
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted
  listen: "zabbix" 
