---
# handlers file for nginx_custom
- name: Nginx Reloader
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
  listen: "Nginx Reloader" 
  
- name: PSQL Reloader
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes
  listen: "PSQL Reloader" 
