---
# tasks file for psql_cluster
- name: Меняем имя машины
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when: "inventory_hostname != ansible_hostname"

- name: Обновление пакетов
  ansible.builtin.command: "{{ item }}"
  with_items:
    - sudo apt-get update -y
  failed_when: false
  
- name: установка postgresql
  apt:
    name: "postgresql"
    state: present
  notify: "PSQL Reloader"
  
- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql
  
- name: настройка postgresql.conf на мастер ноде
  ansible.builtin.template:
    src: postgresql_master_conf.j2
    dest: /etc/postgresql/14/main/postgresql.conf
  when: "'postgresql-master' in inventory_hostname"
  notify: "PSQL Reloader" 
  
- name: настройка postgresql.conf на реплика ноде
  ansible.builtin.template:
    src: postgresql_slave_conf.j2
    dest: /etc/postgresql/14/main/postgresql.conf
  when: "'postgresql-slave' in inventory_hostname"
  notify: "PSQL Reloader" 
  
- name: настройка pg_hba.conf на мастер ноде
  ansible.builtin.template:
    src: pg_hba_conf_master.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
  #when: "'postgresql-master' in inventory_hostname"
  notify: "PSQL Reloader" 
  
- name: настройка postgresql - создание пользователя для БД медиавики
  ansible.builtin.expect:
    command: sudo -u postgres createuser -S -D -R -P -E wikiuser
    responses:
      Enter password for new role: "12345678"
      Enter it again: "12345678"
  when: "'postgresql-master' in inventory_hostname"
  failed_when: false
  
- name: Создаем БД и выдаем права на БД пользователю
  ansible.builtin.command: "{{ item }}"
  with_items:
    - sudo -u postgres createdb -O wikiuser my_wiki
  when: "'postgresql-master' in inventory_hostname"
  failed_when: false
  
- name: установка cifs-utils
  apt:
    name: "cifs-utils"
    state: present
  #when: "'postgresql-master' in inventory_hostname"

- name: добавление строки в fstab адрес файлового сервера
  lineinfile:
    dest: /etc/fstab
    line: //192.168.10.38/backupfs /mnt cifs user,rw,noauto,credentials=/root/.smbclient 0 0
  #when: "'postgresql-master' in inventory_hostname"
  
- name: копируем файл с паролем для сетевой папки
  copy:
    src: /home/kongorg/ansible/smbclient    # note the '/' <-- !!!
    dest: /root/.smbclient
  #when: "'postgresql-master' in inventory_hostname"
