---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx_proxy: #Имя подгруппы хостов балансировщика
      hosts: #Узлы группы
        balance-server: #Имя машины
          ansible_host: 158.160.62.236 #Адрес машины
    nginx_custom: #Имя подгруппы хостов серверов приложения
      hosts: #Узлы группы
        mediawiki-node1:
          ansible_host: 158.160.57.149
        mediawiki-node2:
          ansible_host: 89.169.156.118
    psql_cluster: #Имя подгруппы хостов кластера БД
      hosts: #Узлы группы
        postgresql-master:
          ansible_host: 158.160.47.100
        postgresql-slave:
          ansible_host: 158.160.34.246
    monitoring: #Имя подгруппы хостов мониторинга
      hosts: #Узлы группы
        zabbix:
          ansible_host: 84.252.129.47
          ansible_python_interpreter: "{{ ansible_playbook_python }}" 
    backup: #Имя подгруппы хостов мониторинга
      hosts: #Узлы группы
        backup-fs:
          ansible_host: 89.169.130.89


  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "root"
    ansible_become: false #Становиться ли другим пользователем после подключения
