--- 
- name: Установка и настройка nginx c кастомной страницей
  hosts: nginx_custom # Будет работать на узлах в группе nginx_custom
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка проксирующего сервера
  hosts: nginx_proxy # Будет работать на узлах в группе nginx_proxy
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Установка и настройка кластера БД
  hosts: psql_cluster # Будет работать на узлах в группе psql_cluster
  roles:
    - role: psql_cluster
  tags:
    - psql_cluster

- name: Настройка репликации кластера БД
  hosts: psql_cluster # Будет работать на узлах в группе psql_cluster
  roles:
    - role: replica
  tags:
    - replica

- name: Настройка файлового сервера хранения бэкапов
  hosts: backup
  roles:
    - role: backup
  tags:
    - backup

- name: Настройка расписания выполнения скрипта бэкапа приложения
  hosts: nginx_custom
  roles:
    - role: backup_fs
  tags:
    - backupfs

- name: Настройка расписания выполнения скрипта бэкапа БД
  hosts: psql_cluster
  roles:
    - role: backupdb
  tags:
    - backupdb

- name: копирование файла Localsettings на хосты приложения
  hosts: nginx_custom
  roles:
    - role: mwfinal
  tags:
    - mwfinal

- name: установка zabbix сервера
  hosts: zabbix
  roles:
    - role: zabbix
  tags:
    - zabbix
    
- name: установка zabbix агентов
  hosts: all
  roles:
    - role: zabbix-agent
  tags:
    - zabbix-agent
