---
# tasks file for nginx_custom
- name: Меняем имя машины
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when: "inventory_hostname != ansible_hostname"
  
- name: Обновление пакетов
  ansible.builtin.command: "{{ item }}"
  with_items:
    - sudo apt-get update -y
  failed_when: false

- name: Установка Nginx и необходимых пакетов
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages_to_install }}"

- name: Копируем файлы MediaWiki на удаленный веб-сервер
  copy:
    src: /home/kongorg/ansible/mediawiki-1.42.1.tar.gz    # note the '/' <-- !!!
    dest: /tmp
  
- name: Распаковываем архив на удаленной машине
  ansible.builtin.command: "{{ item }}"
  with_items:
    - tar -xvf /tmp/mediawiki-1.42.1.tar.gz -C /tmp
    - sudo mv /tmp/mediawiki-1.42.1 /var/www/mediawiki
    - sudo chown -R www-data:www-data /var/www/mediawiki
    - sudo chmod -R 755 /var/www/mediawiki
  failed_when: false
  
- name: Копируем файл сетевый настроек mediawiki на удаленный веб-сервер
  copy:
    src: /home/kongorg/ansible/mediawiki    # note the '/' <-- !!!
    dest: /etc/nginx/sites-available/
  notify: "Nginx Reloader"
  
- name: символьная ссылка
  ansible.builtin.command: "{{ item }}"
  with_items:
    - sudo ln -s /etc/nginx/sites-available/mediawiki /etc/nginx/sites-enabled/
  notify: "Nginx Reloader"
  failed_when: false

- name: установка cifs-utils
  apt:
    name: "cifs-utils"
    state: present
  when: "'mediawiki-node1' in inventory_hostname"

- name: добавление строки в fstab
  lineinfile:
    dest: /etc/fstab
    line: //192.168.10.38/backupfs /mnt cifs user,rw,noauto,credentials=/root/.smbclient 0 0
  when: "'mediawiki-node1' in inventory_hostname"
  
- name: копируем файл с паролем для сетевой папки
  copy:
    src: /home/kongorg/ansible/smbclient    # note the '/' <-- !!!
    dest: /root/.smbclient
  when: "'mediawiki-node1' in inventory_hostname"
